<?xml version="1.0" encoding="UTF-8"?>
<testsuite hostname="vnvpc130" name="com.qaselenium.NewTest" tests="1" failures="0" timestamp="19 Jun 2012 13:43:47 GMT" time="318.531" errors="0">
  <testcase name="@BeforeClass beforeClass" time="0.0" classname="com.qaselenium.NewTest">
    <failure type="java.lang.RuntimeException" message="Could not contact Selenium Server; have you started it on &amp;apos;localhost:5559&amp;apos; ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect">
      <![CDATA[java.lang.RuntimeException: Could not contact Selenium Server; have you started it on 'localhost:5559' ?
Read more at http://seleniumhq.org/projects/remote-control/not-started.html
Connection refused: connect
	at com.thoughtworks.selenium.DefaultSelenium.start(DefaultSelenium.java:102)
	at com.qaselenium.NewTest.beforeClass(NewTest.java:23)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
... Removed 17 stack frames]]>
    </failure>
  </testcase>
  <testcase name="@AfterClass afterClass" time="0.0" classname="com.qaselenium.NewTest">
    <skipped/>
  </testcase>
  <testcase name="testGoogleSearch" time="0.0" classname="com.qaselenium.NewTest">
    <skipped/>
  </testcase>
</testsuite>
